### PR TITLE
Consolidated callback arguments into RouteContext

### LINKED ISSUE #9: Send extras bundle to RouterCallback
Extras aren't currently passed to RouterCallback so they get lost in the process.

Happy to do a PR for this, but it would break backwards compatibility  unless it introduced a RouterExtrasCallback, which smells bad. Thoughts?

### LINKED ISSUE #12: open() parses URLs multiple times
Router.open() parses the URL parameters once to check for the callback and then again in intentFor(). This could easily be optimised to make use of the RouterParams (which should probably be renamed MatchedRoute to avoid confusion).

Granted, it's a small optimisation given that open() is not expected to be called at high frequency. Still, it doesn't look too difficult to fix.

### PR DESCRIPTION
**Pull request by richardszalay**
Refactored callback arguments to a single RouteContext class, which now includes the parameters, the extras, and the Android context. Resolves #9 

I've also refactored open() so that it no longer parses the URL multiple times (once for callbacks, once for the intent). Resolves #12

### CODE REVIEW

**Comment by clayallsopp** [comment]
Sweet, could you update the `README` accordingly?

**Comment by richardszalay** [comment]
Would you mind if I also fixed #15 as part of this PR? (Saves me faffing around with rebasing new branches we go through them)

**Comment by clayallsopp** [comment]
Go for it, the suggestions look good to me

**Comment by richardszalay** [comment]
Done!

**Comment by clayallsopp** [comment]
:shipit:

**Pull request merged**
